/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pcte;

import static Controller.Conexao.Conectar;
import static Controller.Conexao.con;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Anchieta
 */
public class categoriaConsultar extends javax.swing.JFrame {
    public void campos(boolean acao){
        txtDesc.setEditable(false);
        
    }

    /**
     * Creates new form categoriaConsultar
     */
    public categoriaConsultar() {
        initComponents();
        setLocationRelativeTo(null);
        Conectar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDesc = new javax.swing.JTextArea();
        btnVoltar = new javax.swing.JLabel();
        btnNOVACONSULTA = new javax.swing.JLabel();
        btnCONSULTAR = new javax.swing.JLabel();
        btnALTERAR = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TXTid = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(4, 15, 213));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel2.setFont(new java.awt.Font("Swis721 BlkEx BT", 0, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pcte/CONSULTAR CATEGORIA.png"))); // NOI18N

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nome:");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Descrição");

        txtDesc.setEditable(false);
        txtDesc.setBackground(new java.awt.Color(204, 204, 204));
        txtDesc.setColumns(20);
        txtDesc.setRows(5);
        jScrollPane1.setViewportView(txtDesc);

        btnVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pcte/btnVOLTARMELHOR.png"))); // NOI18N
        btnVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVoltarMouseClicked(evt);
            }
        });

        btnNOVACONSULTA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pcte/btnCONSULTARMELHOR.png"))); // NOI18N
        btnNOVACONSULTA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNOVACONSULTAMouseClicked(evt);
            }
        });

        btnCONSULTAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pcte/btnCONSULTAR.png"))); // NOI18N
        btnCONSULTAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCONSULTARMouseClicked(evt);
            }
        });

        btnALTERAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pcte/btnALTERARMELHOR.png"))); // NOI18N
        btnALTERAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnALTERARMouseClicked(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pcte/Texto do seu parágr (2).png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ID:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(btnCONSULTAR)
                        .addGap(18, 18, 18)
                        .addComponent(btnNOVACONSULTA)
                        .addGap(18, 18, 18)
                        .addComponent(btnALTERAR)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(btnVoltar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane1)
                            .addComponent(txtNome))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel5))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(TXTid, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TXTid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnVoltar, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnCONSULTAR, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(btnNOVACONSULTA, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnALTERAR, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoltarMouseClicked
       this.dispose();
    }//GEN-LAST:event_btnVoltarMouseClicked

    private void btnCONSULTARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCONSULTARMouseClicked
        campos(true);

        String usuario = txtNome.getText();

        try {

            String sql = "SELECT * FROM categoria WHERE nome like ? ";
            PreparedStatement stmt = con.prepareStatement(sql);
            stmt.setString(1, '%'+usuario+'%');
            ResultSet rs = stmt.executeQuery();

            if (rs.next()) {
                TXTid.setText(rs.getString("codCat"));
                txtNome.setText(rs.getString("nome"));
                txtDesc.setText(rs.getString("descricao"));
               


            } else {
                JOptionPane.showMessageDialog(null,"Categoria não encontrado!");
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Erro ao conectar: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnCONSULTARMouseClicked

    private void btnNOVACONSULTAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNOVACONSULTAMouseClicked
        txtNome.setText(" ");
        txtDesc.setText(" ");
    }//GEN-LAST:event_btnNOVACONSULTAMouseClicked

    private void btnALTERARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnALTERARMouseClicked
       int result, opcao;
String sql;
Object[] options = { "Sim", "Não" };

opcao = JOptionPane.showOptionDialog(
        null,
        "Gravar as alterações?",
        "Alteração",
        JOptionPane.YES_NO_OPTION,
        JOptionPane.QUESTION_MESSAGE,
        null,
        options,
        options[1]
);

if (opcao == 0) { // botão "Sim"
    try {
        sql = "UPDATE categoria SET descricao = ? WHERE nome = ? ";

        PreparedStatement stm = con.prepareStatement(sql,
                ResultSet.TYPE_SCROLL_SENSITIVE,
                ResultSet.CONCUR_UPDATABLE
        );

        // A ordem dos parâmetros deve seguir a ordem do SQL
        stm.setString(1, txtDesc.getText()); // novo valor
        stm.setString(2, txtNome.getText()); // condição WHERE

        result = stm.executeUpdate();

        if (result > 0) {
            JOptionPane.showMessageDialog(null, "Dados Alterados com Sucesso!");
        } else {
            JOptionPane.showMessageDialog(null, "Nenhum registro encontrado para alterar!");
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Erro SQL! " + e.getMessage());
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Erro! " + e.getMessage());
    }
} else {
    System.out.println("Alteração cancelada");
}

    }//GEN-LAST:event_btnALTERARMouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        try {
    // 1. Remove vínculo da categoria nos produtos
    String sqlUpdate = "UPDATE produtos SET fk_categoria = NULL WHERE fk_categoria = ?";
    PreparedStatement stmUpdate = con.prepareStatement(sqlUpdate);
    stmUpdate.setString(1, TXTid.getText()); // ID da categoria
    stmUpdate.executeUpdate();

    // 2. Exclui a categoria
    String sqlDelete = "DELETE FROM categoria WHERE codCat = ?";
    PreparedStatement stmDelete = con.prepareStatement(sqlDelete);
    stmDelete.setString(1, TXTid.getText());
    int resultDelete = stmDelete.executeUpdate();

    if (resultDelete > 0) {
        JOptionPane.showMessageDialog(null, "Categoria excluída com sucesso!");
        TXTid.setText(" ");
        txtDesc.setText(" ");
        txtNome.setText(" ");
    } else {
        JOptionPane.showMessageDialog(null, "Categoria não encontrada!");
    }

} catch (SQLException e) {
    JOptionPane.showMessageDialog(null, "Erro ao excluir categoria! " + e.getMessage());
}

    }//GEN-LAST:event_jLabel4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(categoriaConsultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(categoriaConsultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(categoriaConsultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(categoriaConsultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new categoriaConsultar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TXTid;
    private javax.swing.JLabel btnALTERAR;
    private javax.swing.JLabel btnCONSULTAR;
    private javax.swing.JLabel btnNOVACONSULTA;
    private javax.swing.JLabel btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtDesc;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
